version: "3"

services:
  db:
    image: postgres
    container_name: matsuri_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    container_name: matsuri_web
    build: .
    command: >
      sh -c "
        rm -f tmp/pids/server.pid &&
        yarn install &&
        bundle exec rails s -p 3000 -b '0.0.0.0'
      "
    volumes:
      - .:/MATSURI_SERVICE
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  postgres_volume:
